FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json ./
COPY tsconfig.frontend.json ./
COPY src/frontend ./src/frontend

RUN npm ci
RUN npm run build:frontend

FROM nginx:1.27-alpine

COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY public /usr/share/nginx/html
COPY --from=build /app/public/dist /usr/share/nginx/html/dist

EXPOSE 80
