FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma

RUN npm ci
RUN npx prisma generate

COPY src ./src
COPY public ./public
COPY tsconfig*.json ./
COPY prisma.config.ts ./

EXPOSE 4000

CMD ["npx", "tsx", "src/index.ts"]
